import assert from 'node:assert/strict';
import {attendanceEvidence,operationsSignals,makeCase,relatedCase,campusSnapshot,cohortSnapshot,studentProgressReport,dayOffset} from '../lib/operations.ts';
import {validateEnterprise} from '../lib/enterprise.ts';
const day='2026-10-07',campus={id:'c',kind:'campuses',name:'Campus A',status:'Active'},cls={id:'class',kind:'classes',name:'October class',status:'In progress',campusId:'c',capacity:4,startDate:'2026-10-01',endDate:'2026-11-01'};
const s={id:'s',kind:'students',name:'Student A',status:'Yard',campusId:'c',classId:'class',sessions:[],assessments:[],evaluations:[],clpExpiry:'2026-10-20',ssnLast4:'PRIVATE-IDENTITY',drugScreen:{resultStatus:'PRIVATE-RESULT'},documents:[{name:'PRIVATE-UPLOAD'}],notes:[{text:'PRIVATE-CASE'}],tuition:9999};
const mark={id:'old',phase:'Yard',date:day,attendance:'Absent',hours:0,mood:'red',notes:'Corrected error',instructor:'Trainer',createdAt:day+'T09:00:00Z'};
const corrected={...mark,id:'new',correctionOf:'old',attendance:'Present',hours:2,mood:'green',skill:'Straight-line backing',notes:'Reviewed mirror checks',createdAt:day+'T10:00:00Z'};
const later={...corrected,id:'second',correctionOf:undefined,hours:1,createdAt:day+'T11:00:00Z'};
const road={...corrected,id:'road',correctionOf:undefined,phase:'Road',hours:1};
const excused={...mark,id:'excused',date:'2026-10-06',attendance:'Excused',mood:undefined};
const evidence={...s,sessions:[mark,corrected,later,road,excused]};
const a=attendanceEvidence(evidence,'2026-10-01',day);assert.equal(a.recorded,3);assert.equal(a.attended,2);assert.equal(a.absent,0);assert.equal(a.excused,1);assert.equal(a.rate,100);assert.equal(attendanceEvidence(s,day,day).rate,null);
assert.equal(operationsSignals([campus,cls,evidence],day).some(x=>x.category==='Attendance support'),false);
assert.equal(operationsSignals([campus,cls,evidence],day).some(x=>x.title.includes('intervention')),false);
const future={...mark,id:'future',date:'2026-10-08'};assert.equal(operationsSignals([{...s,clpExpiry:undefined,sessions:[future]}],day).length,0);
const retake={id:'fail',type:'Theory final',score:70,date:'2026-10-01',remediation:'Repeat review'},pass={...retake,id:'pass',score:85,date:'2026-10-02'};
assert.equal(operationsSignals([{...s,assessments:[retake,pass]}],day).some(x=>x.key.endsWith(':theory')),false);
assert.equal(operationsSignals([{...s,assessments:[retake]}],day).some(x=>x.key.endsWith(':theory')),true);
const signal=operationsSignals([s],day)[0],task=makeCase(signal,[campus,s],day,'t');assert.equal(task.campusId,'c');assert.equal(task.studentId,'s');assert.equal(relatedCase([task],signal).id,'t');assert.equal(relatedCase([{...task,status:'Complete'}],signal),undefined);
const redSignal=operationsSignals([{...s,sessions:[mark]}],day).find(x=>x.sourceEntry==='old');assert.equal(relatedCase([{id:'auto',kind:'tasks',name:'Auto task',status:'Open',sourceEntry:'old'}],redSignal).id,'auto');
assert.match(validateEnterprise(task),/owner/);const valid={...task,owner:'Staff',plan:'Schedule coaching and review the file.'};assert.equal(validateEnterprise(valid),null);assert.match(validateEnterprise({...valid,status:'Complete'}),/outcome/);assert.equal(validateEnterprise({...valid,status:'Complete',outcome:'Review completed and student contacted.'}),null);assert.match(validateEnterprise({...valid,due:'2026-02-30'}),/valid due date/);
const vehicle={id:'v',kind:'fleet',name:'Truck 1',status:'Ready',campusId:'c',unit:'01',maintenanceDue:day};const snapshot=campusSnapshot([campus,cls,s,vehicle],day)[0];assert.equal(snapshot.students,1);assert.equal(snapshot.seats,3);assert.equal(snapshot.vehicles,1);assert.equal(snapshot.high,1);assert.equal(cohortSnapshot([s],cls).seats,3);
const report=studentProgressReport(evidence,[campus,cls,evidence],'2026-10-01',day);assert.match(report,/Yard: 3 instruction hours/);assert.match(report,/Recorded date\/location marks: 3/);assert.doesNotMatch(report,/PRIVATE-|9999|Reviewed mirror checks/);assert.match(studentProgressReport(evidence,[campus,cls,evidence],'2026-10-01',day,true),/Reviewed mirror checks/);
const career={stage:'Placed',employer:'Employer',startDate:day,notes:'Student confirmed employment today.'};assert.equal(validateEnterprise({...s,ssnLast4:undefined,career}),null);assert.match(validateEnterprise({...s,career:{...career,employer:''}}),/employer/);assert.match(validateEnterprise({...s,career:{...career,retention90:'Made up'}}),/retention/);
assert.equal(dayOffset('2026-03-01',-1),'2026-02-28');
console.log('PASS: correction-aware attendance, latest/future evidence, follow-up deduplication, case validation, campus capacity, private report exclusions and career outcome validation.');
