import assert from 'node:assert/strict';
import {instructionHours,activeSessions,theoryState,validateRecord,preserveHistory,duration,latestSkill} from '../lib/training.ts';
import {classSeats,appointmentConflict,validateAdmissions} from '../lib/admissions.ts';
import {trainingFollowUps} from '../lib/actions.ts';
const student={id:'s',kind:'students',name:'Student',status:'Classroom',sessions:[],evaluations:[],assessments:[]};
const final={id:'f',name:'Final',type:'Theory final',score:79,correct:79,total:100,instructor:'Trainer',remediation:'Retake after coaching'};
assert.equal(theoryState({...student,assessments:[final]}).passed,false);
const passed={...final,score:80,correct:80};
assert.equal(theoryState({...student,assessments:[passed]}).passed,true);
assert.equal(theoryState({...student,assessments:[passed]}).signed,false);
const complete={...student,assessments:[passed],theorySignoff:{assessmentId:'f',instructor:'Trainer'}};
assert.equal(theoryState(complete).signed,true);
assert.equal(theoryState({...complete,assessments:[passed,{...final,id:'f2'}]}).signed,false);
assert.match(validateRecord({...student,status:'Graduated'}),/theory review/);
const old={id:'entry-1',phase:'Yard',attendance:'Present',hours:2,date:'2026-10-06',instructor:'Trainer',mood:'green'};
const corrected={...old,id:'entry-2',hours:1,correctionOf:'entry-1'};
const observation={...old,id:'observer',mode:'Observation',hours:3};
const absent={...old,id:'absent',attendance:'Absent',hours:0};
assert.equal(instructionHours({...student,sessions:[old,corrected,observation,absent]},'Yard'),1);
assert.equal(activeSessions({...student,sessions:[old,corrected]}).length,1);
assert.match(preserveHistory({...student,sessions:[old]},{...student,sessions:[corrected]}),/overwritten/);
assert.equal(preserveHistory({...student,sessions:[old]},{...student,sessions:[old,corrected]}),null);
assert.match(validateRecord({...student,sessions:[{...old,mood:'red',notes:''}]}),/intervention note/);
const rubric={'Setup and positioning':'Independent','Observation and safety checks':'Independent','Vehicle control':'Independent','Accuracy and completion':'Independent'};
const e={id:'e',phase:'Yard',skill:'90° alley dock',level:'Proficient',rubric,signed:true,instructor:'Trainer',criticalError:false};
assert.equal(validateRecord({...student,evaluations:[e]}),null);
assert.match(validateRecord({...student,evaluations:[{...e,signed:false}]}),/sign-off/);
assert.match(validateRecord({...student,evaluations:[{...e,criticalError:true,notes:'Safety error'}]}),/no critical/);
assert.equal(latestSkill({...student,evaluations:[e,{...e,id:'e2',level:'Needs improvement'}]},e.skill).level,'Needs improvement');
assert.equal(duration('09:00','11:30',30),2);
const cls={id:'class',kind:'classes',name:'Class A',status:'Open for enrollment',capacity:1,startDate:'2026-10-19',endDate:'2026-11-20',program:'Class A'};
assert.equal(classSeats([cls,{...student,classId:'class'}],cls),0);
assert.equal(classSeats([cls,{...student,classId:'class',status:'Withdrawn'}],cls),1);
const ap={id:'a',kind:'appointments',name:'Tour',status:'Scheduled',date:'2026-10-06',start:'09:00',end:'10:00',owner:'Admissions'};
assert.ok(appointmentConflict([ap],{...ap,id:'b',start:'09:30',end:'10:30'}));
assert.equal(appointmentConflict([ap],{...ap,id:'b',start:'10:00',end:'11:00'}),undefined);
assert.match(validateAdmissions({...cls,endDate:'2026-10-01'}),/valid dates/);
let n=0;assert.equal(trainingFollowUps(student,{...student,sessions:[{...old,mood:'red',notes:'Coaching'}],assessments:[final],evaluations:[{...e,criticalError:true,notes:'Safety'}]},'2026-10-06',()=>String(++n)).length,3);
console.log('PASS: 80% boundary, final sign-off, retake blocking, history retention, corrected hours, observation exclusion, proficiency rubric, calendar conflicts, class capacity and automatic follow-ups.');
const {attendanceRoster,attendancePhase}=await import('../lib/attendance.ts');
const moved={...student,status:'Yard',sessions:[{...old,phase:'Classroom'}]};
const road={...student,id:'road',status:'Road'},pending={...student,id:'pending',status:'Enrollment pending'};
assert.equal(attendanceRoster([student,moved,road,pending],'Classroom').length,1);
assert.equal(attendanceRoster([moved],'Classroom').length,0);
assert.equal(attendanceRoster([moved],'Yard')[0].sessions[0].phase,'Classroom');
assert.equal(attendanceRoster([student,moved,road,pending,{...student,status:'Graduated'}],'All students').length,4);
assert.equal(attendancePhase(moved,'All students'),'Yard');
assert.equal(attendancePhase(pending,'All students'),'');
assert.equal(attendancePhase(pending,'All students','Classroom'),'Classroom');
console.log('PASS: location rosters, status transfer, retained classroom history, all-student per-location attendance and pending-location selection.');

const {moduleAllowed,trainingWriter,startModule}=await import('../lib/roles.ts');
assert.equal(moduleAllowed('Owner','setup'),true);
assert.equal(moduleAllowed('Instructor','finance'),false);
assert.equal(moduleAllowed('Instructor','tasks'),true);
assert.equal(moduleAllowed('Front desk','settings'),false);
assert.equal(moduleAllowed('Enrollment specialist','students'),true);
assert.equal(trainingWriter('Enrollment specialist'),false);
assert.equal(trainingWriter('Campus manager'),true);
assert.equal(startModule('Front desk'),'calendar');
console.log('PASS: employee navigation, training review permissions and role start pages.');
