import {randomBytes,scrypt,timingSafeEqual,createHash} from 'node:crypto';
import {sql} from '../lib/storage';
export const digest=(text:string)=>createHash('sha256').update(text).digest('hex');
const token=()=>randomBytes(32).toString('base64url');
import {hashPassword,verifyPassword} from './password';
export function activation(account:string){const raw=token();sql.prepare('DELETE FROM activations WHERE account = ?').run(account);sql.prepare('INSERT INTO activations(token,account,expires) VALUES(?,?,?)').run(digest(raw),account,Date.now()+30*60*1000);return raw;}
export function issueSession(account:string){const raw=token();sql.prepare('DELETE FROM sessions WHERE expires < ?').run(Date.now());sql.prepare('INSERT INTO sessions(token,account,expires) VALUES(?,?,?)').run(digest(raw),account,Date.now()+8*60*60*1000);return raw;}
export function sessionUser(req:Request){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)academy_session=([^;]+)/)?.[1];if(!raw)return null;const row:any=sql.prepare('SELECT a.id,a.email FROM accounts a JOIN sessions s ON s.account=a.id WHERE s.token = ? AND s.expires > ? AND a.active = 1').get(digest(raw),Date.now());return row?{userId:row.id,email:row.email,displayName:row.email}:null;}
export function sessionCookie(value:string,maxAge=8*3600){return 'academy_session='+value+'; HttpOnly; SameSite=Lax; Path=/; Max-Age='+maxAge+(process.env.NODE_ENV==='production'?'; Secure':'');}
export function allowedOrigin(req:Request){return req.headers.get('origin')===new URL(process.env.PUBLIC_ORIGIN||req.url).origin;}
export function rateLimit(ip:string,email:string){const key=digest(ip+'|'+email.toLowerCase()),now=Date.now();sql.prepare('DELETE FROM attempts WHERE expires < ?').run(now);const old:any=sql.prepare('SELECT count FROM attempts WHERE key = ?').get(key);if(old?.count>=5)return false;sql.prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').run(key,now+15*60*1000);return true;}
export async function authenticate(req:Request,ip:string){if(!allowedOrigin(req))return Response.json({error:'Invalid origin'},{status:403});const body:any=await req.json();const email=String(body.email||'').trim().toLowerCase();if(typeof body.password!=='string'||body.password.length>256||!rateLimit(ip,email))return Response.json({error:'Unable to sign in. Try again later.'},{status:429});const account:any=sql.prepare('SELECT * FROM accounts WHERE email = ? AND active = 1').get(email);const valid=account?.password?await verifyPassword(body.password,account.password):await verifyPassword(body.password,'00000000000000000000000000000000:'+('00'.repeat(64)));if(!account||!valid)return Response.json({error:'Email or password is incorrect.'},{status:401});if(account.id!=='academy-owner'){const staff:any=sql.prepare("SELECT id FROM records WHERE owner = 'academy-owner' AND kind='staff' AND lower(json_extract(payload,'$.email')) = ? AND json_extract(payload,'$.status')='Active'").get(email);if(!staff)return Response.json({error:'Your school access is inactive. Contact your administrator.'},{status:403});}return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie(issueSession(account.id))}});}
export async function activate(req:Request,ip:string){if(!allowedOrigin(req))return Response.json({error:'Invalid origin'},{status:403});const b:any=await req.json();if(typeof b.token!=='string'||b.token.length>128||!rateLimit(ip,digest(b.token)))return Response.json({error:'Activation unavailable. Try again later.'},{status:429});if(typeof b.password!=='string'||b.password.length<14||b.password.length>256)return Response.json({error:'Use a password with 14–256 characters.'},{status:400});const row:any=sql.prepare('SELECT * FROM activations WHERE token = ? AND expires > ?').get(digest(b.token),Date.now());if(!row)return Response.json({error:'This activation link is expired or already used.'},{status:400});const password=await hashPassword(b.password);sql.exec('BEGIN IMMEDIATE');try{const result=sql.prepare('DELETE FROM activations WHERE token = ? AND expires > ?').run(digest(b.token),Date.now());if(!result.changes)throw Error('Activation already used');sql.prepare('UPDATE accounts SET password = ? WHERE id = ?').run(password,row.account);sql.prepare('DELETE FROM sessions WHERE account = ?').run(row.account);sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');return Response.json({error:'Activation link was already used.'},{status:409});}return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie(issueSession(row.account))}});}
