import {createServer} from 'node:http';
import {readFileSync,existsSync,statSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {identity} from './context';
import {sql} from '../lib/storage';
import {authenticate,activate,activation,sessionUser,sessionCookie,allowedOrigin,digest} from './auth';
import {getWorkspaceAccess} from '../lib/workspace-access';
import * as records from '../app/api/records/route';
import * as files from '../app/api/files/route';
import * as communications from '../app/api/communications/route';
import * as integrations from '../app/api/integrations/route';
export async function handle(req:Request,ip='local'):Promise<Response>{const url=new URL(req.url);if(req.method==='POST'&&!allowedOrigin(req))return Response.json({error:'Invalid origin'},{status:403});
 if(url.pathname==='/api/auth/login'&&req.method==='POST')return authenticate(req,ip);
 if(url.pathname==='/api/auth/activate'&&req.method==='POST')return activate(req,ip);
 if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)academy_session=([^;]+)/)?.[1];if(raw)sql.prepare('DELETE FROM sessions WHERE token = ?').run(digest(raw));return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie('',0)}});}
 return identity.run(sessionUser(req)||undefined as any,async()=>{const access=await getWorkspaceAccess();if(url.pathname==='/api/auth/me')return access?Response.json({email:access.user.email,role:access.role}):Response.json({error:'Sign in required'},{status:401});
 if(url.pathname==='/api/accounts/invite'&&req.method==='POST'){if(access?.role!=='Owner')return Response.json({error:'Owner access required'},{status:403});const b:any=await req.json();const row:any=sql.prepare("SELECT payload FROM records WHERE id=? AND owner='academy-owner' AND kind='staff'").get(b.staffId);const staff=row?JSON.parse(row.payload):null;if(!staff||staff.status!=='Active'||!staff.accessRole||!staff.campusIds?.length||!/^\S+@\S+\.\S+$/.test(staff.email||''))return Response.json({error:'Save an active employee with a valid email, role and assigned campuses.'},{status:400});const email=staff.email.toLowerCase();let account:any=sql.prepare('SELECT id FROM accounts WHERE email=?').get(email);if(account?.id==='academy-owner')return Response.json({error:'Owner account cannot be reset through employee setup.'},{status:400});if(!account){account={id:randomUUID()};sql.prepare('INSERT INTO accounts(id,email) VALUES(?,?)').run(account.id,email);}return Response.json({link:new URL('/activate',process.env.PUBLIC_ORIGIN||url.origin).href+'#token='+activation(account.id),expiresMinutes:30},{headers:{'Cache-Control':'no-store'}});}
 const routes:any={'/api/records':records,'/api/files':files,'/api/communications':communications,'/api/integrations':integrations};if(routes[url.pathname]){const fn=routes[url.pathname][req.method];if(!fn)return new Response('Method not allowed',{status:405});return fn(req);}if(url.pathname.startsWith('/api/'))return new Response('Not found',{status:404});
 const root=resolve('dist'),requested=resolve(root,'.'+decodeURIComponent(url.pathname));const safe=requested===root||requested.startsWith(root+'/');const path=safe&&existsSync(requested)&&statSync(requested).isFile()?requested:resolve(root,'index.html');if(!existsSync(path))return new Response('Build the frontend first',{status:503});const ext=path.split('.').at(-1),mime:any={html:'text/html',js:'text/javascript',css:'text/css',svg:'image/svg+xml',png:'image/png',ico:'image/x-icon'};return new Response(readFileSync(path),{headers:{'Content-Type':mime[ext!]||'application/octet-stream','Cache-Control':ext==='html'?'no-store':'public, max-age=3600','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'"}});
 });}
if(process.env.ACADEMY_TEST!=='true'){if(process.env.NODE_ENV==='production'&&(!/^https:\/\//.test(process.env.PUBLIC_ORIGIN||'')||!process.env.RECORDS_ENCRYPTION_KEY))throw Error('PUBLIC_ORIGIN and RECORDS_ENCRYPTION_KEY required for production.');createServer(async(incoming,out)=>{try{const chunks:Buffer[]=[];let size=0;for await(const chunk of incoming){size+=chunk.length;if(size>12_000_000){out.writeHead(413);out.end('Request too large');return;}chunks.push(chunk);}const host=process.env.PUBLIC_ORIGIN||'http://127.0.0.1:'+ (process.env.PORT||3000);const headers=new Headers();for(const [k,v]of Object.entries(incoming.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);const request=new Request(new URL(incoming.url||'/',host),{method:incoming.method,headers,...(!['GET','HEAD'].includes(incoming.method||'GET')?{body:Buffer.concat(chunks)}:{})});const result=await handle(request,incoming.socket.remoteAddress||'unknown');out.writeHead(result.status,Object.fromEntries(result.headers));out.end(Buffer.from(await result.arrayBuffer()));}catch{out.writeHead(500,{'Content-Type':'application/json'});out.end(JSON.stringify({error:'Request unavailable'}));}}).listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('KTWS Academy OS independent server listening'));}
