import {RecordData as R,instructionHours,latestSkill,skills,theoryState} from './training';
export const docCategories=['Enrollment agreement','Drug screen authorization','Drug screen result','Commercial learner permit','Driver license','Driver record','SSN evidence','Medical qualification evidence','Funding authorization','Signed contract','MOU','Other'];
export const restrictedCategories=['SSN evidence','Drug screen result','Drug screen authorization','Medical qualification evidence'];
export const programWeeks=[{week:1,title:'Theory & fundamentals',focus:'ELDT theory, quizzes and the theory final',phase:'Classroom'},{week:2,title:'Pre-trip & vehicle inspection',focus:'Inspection routines, vehicle components and study',phase:'Yard'},{week:3,title:'Maneuvers & control',focus:'Straight-line backing, offsets and 90° alley dock',phase:'Yard'},{week:4,title:'Road training',focus:'On-road skills, routes and recorded day/night sessions',phase:'Road'},{week:5,title:'Skills review & test preparation',focus:'Combined skill review, test evidence and graduation review',phase:'Combined'}];
export function campusOf(r:R,all:R[]):string{if(r.kind==='campuses')return r.id;if(r.campusId)return r.campusId;if(r.classId)return all.find(x=>x.id===r.classId)?.campusId||'__legacy__';const related=r.studentId||r.personId||r.leadId;if(related){const p=all.find(x=>x.id===related);if(p&&p.id!==r.id)return p.campusId||(p.classId?all.find(x=>x.id===p.classId)?.campusId:undefined)||'__legacy__';}return '__legacy__';}
export function campusAllowed(role:string,allowed:string[],r:R,all:R[]){if(role==='Owner')return true;if(['templates','courses','lessons','quizzes'].includes(r.kind)&&!r.campusId)return true;if(r.kind==='staff')return (r.campusIds||[]).some((c:string)=>allowed.includes(c));return allowed.includes(campusOf(r,all));}
export function graduationReadiness(s:R){const gaps:string[]=[];if(!theoryState(s).signed)gaps.push('Theory final and completion review');for(const [p,k]of [['Yard','targetYard'],['Road','targetRoad']])if(instructionHours(s,p)<Number(s[k]||0))gaps.push(p+' planned hours');for(const p of ['Yard','Road'] as const)for(const skill of skills[p])if(latestSkill(s,skill)?.level!=='Proficient')gaps.push(skill+' proficiency');if(s.testResult!=='Passed')gaps.push('Documented skills test pass');return {gaps,ready:gaps.length===0};}
export function validateEnterprise(r:R){if(r.kind==='students'){if(r.ssn&&String(r.ssn).length>4)return 'Store only SSN last four digits in profile fields; use restricted encrypted evidence for the full document.';if(r.ssnLast4&&!/^\d{4}$/.test(r.ssnLast4))return 'SSN last four must be four digits.';if(r.status==='Graduated'&&(!r.graduationReview?.instructor||!r.graduationReview?.date||!graduationReadiness(r).ready))return 'Complete the graduation evidence review before marking the student graduated.';}if(r.kind==='contracts'&&r.status==='Completed'&&!r.completedFile?.key)return 'Attach the completed signed contract before recording completion.';if(r.kind==='tpr'&&r.status==='Confirmed'&&!r.confirmationReference)return 'Record the FMCSA confirmation reference.';return null;}
export function renderTemplate(text:string,s:R,c?:R){const vars:any={student_name:s.name,first_name:s.name.split(' ')[0],class_name:c?.name||s.cohort||'',start_date:c?.startDate||s.startDate||'',campus_name:s.campusName||'',school_name:'KTWS Academy'};return text.replace(/\{\{(\w+)\}\}/g,(all,k)=>vars[k]??all);}
