export type RecordData={id:string;kind:string;name:string;status:string;revision?:number;[key:string]:any};
export const phases=['Classroom','Yard','Road'] as const;
export const moods={green:{face:'☺',label:'On track'},yellow:{face:'😐',label:'Needs coaching'},red:{face:'☹',label:'Needs intervention'}};
export const skills={Classroom:['Vehicle systems','Safe operating procedures','Hours of service','Trip planning','Hazard awareness'],Yard:['Pre-trip inspection','Coupling / uncoupling','Straight-line backing','Offset backing — left','Offset backing — right','90° alley dock'],Road:['Vehicle control','Shifting / speed management','Lane positioning','Turns / intersections','Space management','Hazard response','Railroad crossings']};
export const criteria={Classroom:['Explains concept correctly','Applies concept to a scenario','Demonstrates understanding independently'],Yard:['Setup and positioning','Observation and safety checks','Vehicle control','Accuracy and completion'],Road:['Observation and judgment','Vehicle control','Traffic / speed compliance','Safe space management']};
export const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/New_York'});
export function activeSessions(s:RecordData){const all=s.sessions||[];const replaced=new Set(all.map((x:any)=>x.correctionOf).filter(Boolean));return all.filter((x:any)=>!replaced.has(x.id));}
export function instructionHours(s:RecordData,phase?:string){return activeSessions(s).filter((x:any)=>['Present','Late','Left early'].includes(x.attendance)&&x.mode!=='Observation'&&(!phase||x.phase===phase)).reduce((n:number,x:any)=>n+Number(x.hours||0),0);}
export function latestDaily(s:RecordData,phase:string,day?:string){return activeSessions(s).filter((x:any)=>x.phase===phase&&(!day||x.date===day)).sort((a:any,b:any)=>(a.date+(a.createdAt||'')).localeCompare(b.date+(b.createdAt||''))).at(-1);}
export function latestSkill(s:RecordData,skill:string){return (s.evaluations||[]).filter((x:any)=>x.skill===skill).at(-1);}
export function latestFinal(s:RecordData){return (s.assessments||[]).filter((a:any)=>a.type==='Theory final').at(-1);}
export function theoryState(s:RecordData){const final=latestFinal(s);const passed=!!final&&Number(final.score)>=80;const hoursMet=instructionHours(s,'Classroom')>=Number(s.targetTheory||0);const signed=!!s.theorySignoff&&s.theorySignoff.assessmentId===final?.id&&passed&&hoursMet;return {final,passed,hoursMet,signed,label:signed?'Theory complete':passed&&!hoursMet?'Final passed • planned hours incomplete':passed?'Final passed • review pending':final?'Retake / remediation required':'Final assessment pending'};}
export function gradeSummary(s:RecordData){const a=s.assessments||[];return {attempts:a.length,average:a.length?Math.round(a.reduce((n:number,x:any)=>n+Number(x.score),0)/a.length):null,below:a.filter((x:any)=>Number(x.score)<80).length};}
export function duration(start:string,end:string,breakMinutes:number){const a=start.split(':').map(Number),b=end.split(':').map(Number);return Math.max(0,Math.round(((b[0]*60+b[1]-a[0]*60-a[1]-breakMinutes)/60)*100)/100);}
export function validateRecord(r:RecordData){
 if(typeof r.id!=='string'||r.id.length>100||typeof r.name!=='string'||!r.name.trim()||r.name.length>200)return 'A valid name and record ID are required.';
 for(const key of ['sessions','evaluations','assessments','documents'])if(r[key]!=null&&!Array.isArray(r[key]))return 'Invalid '+key;
 for(const s of r.sessions||[]){if(!phases.includes(s.phase)||!['Present','Absent','Excused','Late','Left early'].includes(s.attendance)||!Number.isFinite(Number(s.hours))||Number(s.hours)<0||Number(s.hours)>1000)return 'Invalid attendance or instruction hours.';if(s.mood&&!Object.keys(moods).includes(s.mood))return 'Invalid progress rating.';if(s.mood==='red'&&!s.notes?.trim())return 'Red ratings require an intervention note.';if(s.id&&(!s.instructor?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(s.date)||Number(s.hours)>12))return 'Daily entries require a date, instructor and at most 12 hours.';if(s.id&&s.attendance!=='Absent'&&s.attendance!=='Excused'&&s.start&&s.end&&(s.end<=s.start||Math.abs(duration(s.start,s.end,Number(s.breakMinutes||0))-Number(s.hours))>.02))return 'Instruction hours must match the recorded time and breaks.';if(['Absent','Excused'].includes(s.attendance)&&Number(s.hours)!==0)return 'Absent and excused entries must have zero hours.';}
 for(const a of r.assessments||[]){if(!a.id||!a.instructor?.trim()||!Number.isFinite(Number(a.score))||Number(a.score)<0||Number(a.score)>100||!['Quiz','Theory final','Practical assessment'].includes(a.type))return 'Invalid assessment.';if(a.total!=null&&(!Number.isInteger(Number(a.total))||Number(a.total)<1||!Number.isInteger(Number(a.correct))||Number(a.correct)<0||Number(a.correct)>Number(a.total)||Math.abs(Number(a.score)-Math.round(Number(a.correct)/Number(a.total)*10000)/100)>.01))return 'Grade must match the number of correct answers.';if(Number(a.score)<80&&!a.remediation?.trim())return 'Scores below 80% require a remediation plan.';}
 for(const e of r.evaluations||[]){if(!e.id||!e.instructor?.trim()||!phases.includes(e.phase)||!skills[e.phase as keyof typeof skills].includes(e.skill))return 'Invalid skill evaluation.';if(e.level==='Proficient'&&(!e.signed||e.criticalError||criteria[e.phase as keyof typeof criteria].some(c=>e.rubric?.[c]!=='Independent')))return 'Proficiency requires independent performance in each criterion, no critical errors and instructor sign-off.';if(e.criticalError&&!e.notes?.trim())return 'Critical errors require a note.';}
 if(r.theorySignoff&&!theoryState(r).signed)return 'Theory sign-off requires the latest theory final score to be at least 80% and the school’s planned classroom hours to be recorded.';
 if(['Test preparation','Graduated'].includes(r.status)&&r.kind==='students'&&!theoryState(r).signed)return 'Complete the theory review and 80% final requirement before marking test preparation or graduation.';
 return null;
}
export function preserveHistory(old:RecordData,next:RecordData){for(const key of ['sessions','evaluations','assessments']){const prev=old[key]||[],arr=next[key]||[];if(arr.length<prev.length)return 'Training history cannot be deleted.';for(let i=0;i<prev.length;i++)if(JSON.stringify(prev[i])!==JSON.stringify(arr[i]))return 'Saved training history cannot be overwritten. Add a correction or a new evaluation.';}return null;}
