import {getWorkspaceAccess,canWrite,canRead,projectRecord} from '../../../lib/workspace-access';
import {database} from '../../../lib/storage';
import {validateRecord,preserveHistory,today,RecordData as R} from '../../../lib/training';
import {validateAdmissions,appointmentConflict,classRoster,enrollmentChecks} from '../../../lib/admissions';
export const dynamic='force-dynamic';
import {campusAllowed,campusOf,validateEnterprise} from '../../../lib/enterprise';
import {trainingFollowUps} from '../../../lib/actions';
const kinds=['students','leads','tasks','fleet','funding','finance','courses','staff','settings','quizzes','lessons','schedules','classes','appointments','enrollments','campuses','partners','mous','contracts','templates','messages','tpr'];
export async function GET(){const access=await getWorkspaceAccess();if(!access)return Response.json({error:'Sign in required'},{status:401});try{const db=database();const rows=await db.prepare('SELECT * FROM records WHERE owner = ? ORDER BY updated DESC').bind(access.scope).all();const log=await db.prepare("SELECT id,owner,record_id,action,at,payload,actor,revision FROM audit WHERE owner = ? AND record_id != '__workspace__' ORDER BY at DESC LIMIT 200").bind(access.scope).all();return Response.json({records:rows.results.filter((r:any)=>canRead(access.role,r.kind)&&campusAllowed(access.role,access.campusIds,{...JSON.parse(r.payload),id:r.id,kind:r.kind},rows.results.map((x:any)=>JSON.parse(x.payload)))).map((r:any)=>projectRecord({...JSON.parse(r.payload),id:r.id,kind:r.kind,revision:r.revision},access.role)),audit:['Instructor','Front desk'].includes(access.role)?[]:log.results.filter((l:any)=>{const record:any=rows.results.find((x:any)=>x.id===l.record_id);return access.role==='Owner'||(record&&campusAllowed(access.role,access.campusIds,JSON.parse(record.payload),rows.results.map((x:any)=>JSON.parse(x.payload))));}),workspace:{role:access.role,shared:access.scope!==access.user.userId,campusIds:access.campusIds}},{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('Record load unavailable',e);return Response.json({error:'Unable to load records. Please retry.'},{status:503});}}
export async function POST(req:Request){const access=await getWorkspaceAccess();if(!access)return Response.json({error:'Sign in required'},{status:401});if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid origin'},{status:403});
 try{const body:any=await req.json(),list:R[]=body.records;if(!Array.isArray(list)||!list.length||list.length>60||new Set(list.map(r=>r.id)).size!==list.length)return Response.json({error:'Invalid record batch'},{status:400});const db=database(),now=new Date().toISOString();const guard:any=await db.prepare("SELECT MAX(revision) AS revision FROM audit WHERE owner = ? AND record_id = '__workspace__'").bind(access.scope).first();const guardRevision=Number(guard?.revision||0)+1;const rows=await db.prepare('SELECT * FROM records WHERE owner = ?').bind(access.scope).all();const current:R[]=rows.results.map((r:any)=>({...JSON.parse(r.payload),id:r.id,kind:r.kind,revision:r.revision}));const updates:R[]=[];const proposed=[...current.filter(x=>!list.some(r=>r.id===x.id)),...list];
 for(let r of list){if(!canWrite(access.role,r.kind))return Response.json({error:'Your school role cannot change this record.'},{status:403});if(!r||!kinds.includes(r.kind)||JSON.stringify(r).length>300000)return Response.json({error:'Invalid record'},{status:400});const problem=validateRecord(r)||validateAdmissions(r)||validateEnterprise(r);if(problem)return Response.json({error:problem},{status:400});const old=current.find(x=>x.id===r.id);if(!campusAllowed(access.role,access.campusIds,r,[...current,...list])||(old&&!campusAllowed(access.role,access.campusIds,old,current)))return Response.json({error:'This record is outside your campus access.'},{status:403});if(access.role==='Instructor'&&r.kind==='students'){if(!old)return Response.json({error:'Instructors cannot create enrollment records.'},{status:403});if(r.status!==old.status&&!['Classroom','Yard','Road'].includes(r.status))return Response.json({error:'Instructors can only change classroom, yard or road location.'},{status:403});r={...old,status:r.status,sessions:r.sessions||old.sessions,evaluations:r.evaluations||old.evaluations,assessments:r.assessments||old.assessments,theorySignoff:r.theorySignoff,revision:r.revision};}if(old&&(old.revision!==r.revision||old.kind!==r.kind))return Response.json({error:'This record changed. Reload before saving.'},{status:409});if(!old){const collision=await db.prepare('SELECT id FROM records WHERE id = ?').bind(r.id).first();if(collision)return Response.json({error:'Record ID is already in use'},{status:409});}if(old&&['Enrollment specialist','Admin assistant'].includes(access.role)&&r.kind==='students'&&(['sessions','evaluations','assessments'].some(k=>JSON.stringify(old[k]||[])!==JSON.stringify(r[k]||[]))||JSON.stringify(old.theorySignoff)!==JSON.stringify(r.theorySignoff)))return Response.json({error:'Training evaluations require an instructor or campus manager.'},{status:403});if(old){const p=preserveHistory(old,r);if(p)return Response.json({error:p},{status:400});}
 for(const field of ['classId','studentId','personId','leadId','unitId','partnerId','sponsorId']){if(r[field]){const linked=proposed.find(x=>x.id===r[field]);if(linked&&!campusAllowed(access.role,access.campusIds,linked,proposed))return Response.json({error:'Linked record is outside your campus access.'},{status:403});}}if(r.kind==='students'&&r.classId&&r.campusId){const cls=proposed.find(x=>x.id===r.classId);if(cls&&campusOf(cls,proposed)!==r.campusId)return Response.json({error:'Student campus must match the assigned class campus.'},{status:400});}
 if(r.kind==='messages'&&!['Draft'].includes(r.status))return Response.json({error:'Use the communications send action to record provider status.'},{status:400});if(r.kind==='staff'&&r.accessRole&&!['Campus manager','Enrollment specialist','Admin assistant','Front desk','Instructor'].includes(r.accessRole))return Response.json({error:'Invalid school access role.'},{status:400});const next={...r};for(const key of ['sessions','evaluations','assessments'])if(next[key])next[key]=next[key].map((entry:any,i:number)=>i<(old?.[key]?.length||0)?entry:{...entry,actor:access.user.email,recordedAt:now});if(next.theorySignoff&&JSON.stringify(next.theorySignoff)!==JSON.stringify(old?.theorySignoff))next.theorySignoff={...next.theorySignoff,actor:access.user.email,at:now};if(next.kind==='students'){for(const a of (next.assessments||[]).slice(old?.assessments?.length||0)){if(a.assessmentId){const q=current.find(x=>x.id===a.assessmentId&&x.kind==='quizzes');if(!q?.questions?.length||JSON.stringify(a.questionSnapshot)!==JSON.stringify(q.questions))return Response.json({error:'Assessment version changed. Reload the question set.'},{status:409});const total=q.questions.length,correct=q.questions.filter((v:any)=>a.answers?.[v.id]===String(v.correct)).length;if(q.questions.some((v:any)=>!Object.hasOwn(a.answers||{},v.id))||a.total!==total||a.correct!==correct||a.type!==q.type||a.name!==q.name)return Response.json({error:'Assessment answers and grade do not match the saved question set.'},{status:400});}}}updates.push(next);updates.push(...trainingFollowUps(old,next,today(),()=>crypto.randomUUID()));
 }
 const merged=()=>[...current.filter(r=>!updates.some(x=>x.id===r.id)),...updates];
 for(const r of updates){if(r.kind==='students'&&r.classId){const c=merged().find(x=>x.id===r.classId&&x.kind==='classes');if(!c)return Response.json({error:'Selected class does not exist.'},{status:400});if(classRoster(merged(),c.id).length>Number(c.capacity))return Response.json({error:'Class is full. Choose another class or waitlist the application.'},{status:409});if(r.sourceLead&&merged().filter(x=>x.kind==='students'&&x.sourceLead===r.sourceLead).length>1)return Response.json({error:'This lead is already enrolled.'},{status:409});if(!updates.some(x=>x.id===c.id))updates.push({...c});}
 if(r.kind==='classes'&&classRoster(merged(),r.id).length>Number(r.capacity))return Response.json({error:'Class capacity is below its enrolled roster.'},{status:400});
 if(r.kind==='appointments'){const clash=appointmentConflict(merged(),r);if(clash)return Response.json({error:'Appointment conflict with '+clash.name},{status:409});}
 if(r.kind==='schedules'&&r.status==='Scheduled'){const appointmentClash=appointmentConflict(merged(),r);if(appointmentClash)return Response.json({error:'Calendar conflict with '+appointmentClash.name},{status:409});const unit=merged().find(x=>x.id===r.unitId);if(unit&&unit.status!=='Ready')return Response.json({error:'Training vehicle is unavailable.'},{status:409});const clash=merged().find(x=>x.kind==='schedules'&&x.id!==r.id&&x.status==='Scheduled'&&x.date===r.date&&x.start<r.end&&x.end>r.start&&((x.unitId&&x.unitId===r.unitId)||x.studentId===r.studentId||x.instructor===r.instructor));if(clash)return Response.json({error:'Training schedule conflict with '+clash.name},{status:409});}
 if(r.kind==='leads'&&r.status==='Enrolled'&&!merged().some(x=>x.kind==='students'&&x.id===r.studentId&&x.sourceLead===r.id))return Response.json({error:'Use the enrollment workflow to create and link the student record.'},{status:400});if(r.kind==='enrollments'&&r.status==='Enrolled'){const cls=merged().find(c=>c.id===r.classId&&c.kind==='classes');if(!cls||!['Open for enrollment','In progress'].includes(cls.status))return Response.json({error:'This class is not open for enrollment.'},{status:400});if(['Agency sponsorship','Employer sponsorship'].includes(r.fundingMethod)&&!merged().some(x=>x.kind==='funding'&&x.id===r.sponsorId))return Response.json({error:'Select the funding agency or employer.'},{status:400});if(r.fundingMethod==='Pending authorization')return Response.json({error:'Resolve funding authorization before confirming enrollment.'},{status:400});if(!enrollmentChecks.every(k=>r.checks?.[k]))return Response.json({error:'Complete the enrollment review checklist.'},{status:400});if(Number(r.deposit||0)>Number(r.tuition||0)||Number(r.deposit||0)<0)return Response.json({error:'Deposit cannot exceed tuition.'},{status:400});if(!merged().some(s=>s.kind==='students'&&s.id===r.studentId&&s.classId===r.classId))return Response.json({error:'Enrollment must include its student record and selected class.'},{status:400});}
 }
 for(const contract of updates.filter(r=>r.kind==='contracts'&&r.status==='Completed')){const old=current.find(r=>r.id===contract.id);if(old?.status==='Completed')continue;const s=merged().find(r=>r.id===contract.studentId&&r.kind==='students');if(!s)return Response.json({error:'Contract requires a student record.'},{status:400});const meta:any=await db.prepare('SELECT key FROM school_files WHERE key = ? AND owner = ? AND student = ?').bind(contract.completedFile.key,access.scope,s.id).first();if(!meta)return Response.json({error:'Upload the signed contract into this student’s file first.'},{status:400});const next={...s,documents:[...(s.documents||[]),{...contract.completedFile,category:'Signed contract',name:contract.name+' — signed',verified:true,reviewedAt:now,contractId:contract.id}]};const index=updates.findIndex(r=>r.id===s.id);if(index>=0)updates[index]=next;else updates.push(next);}
 const stmts=[db.prepare('INSERT INTO audit (id,owner,record_id,action,at,payload,revision,actor,snapshot) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),access.scope,'__workspace__','Transaction',now,'{}',guardRevision,access.user.email,'{}')];for(const r of updates){const old=current.find(x=>x.id===r.id),rev=old?Number(old.revision)+1:1;r.revision=rev;const snapshot=JSON.stringify(r);stmts.push(db.prepare('INSERT INTO records (id,owner,kind,payload,revision,updated) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,revision=excluded.revision,updated=excluded.updated WHERE records.owner=excluded.owner AND records.revision=?').bind(r.id,access.scope,r.kind,snapshot,rev,now,old?.revision||0));stmts.push(db.prepare('INSERT INTO audit (id,owner,record_id,action,at,payload,revision,actor,snapshot) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),access.scope,r.id,old?'Updated':'Created',now,JSON.stringify({name:r.name,kind:r.kind}),rev,access.user.email,snapshot));}await db.batch(stmts);return Response.json({ok:true,records:updates.filter(r=>canRead(access.role,r.kind)&&campusAllowed(access.role,access.campusIds,r,merged())).map(r=>projectRecord(r,access.role))});
 }catch(e:any){console.error('Record save failed',e);if(String(e?.message).includes('UNIQUE'))return Response.json({error:'A record changed during saving. Reload and retry; no partial changes were saved.'},{status:409});return Response.json({error:'Save failed. Your input has been kept.'},{status:503});}
}
