import {randomBytes,createHash} from 'node:crypto';
import {hashPassword,verifyPassword} from '../server/password';
import {database,env} from './runtime';
export const digest=(text:string)=>createHash('sha256').update(text).digest('hex');
const token=()=>randomBytes(32).toString('base64url');
export const sessionCookie=(value:string,maxAge=8*3600)=>'academy_session='+value+'; HttpOnly; SameSite=Lax; Path=/; Max-Age='+maxAge+'; Secure';
export const allowedOrigin=(r:Request)=>r.headers.get('origin')===new URL(env.PUBLIC_ORIGIN||r.url).origin;
export async function activation(account:string){const raw=token(),db=database();await db.batch([db.prepare('DELETE FROM activations WHERE account=?').bind(account),db.prepare('INSERT INTO activations(token,account,expires) VALUES(?,?,?)').bind(digest(raw),account,Date.now()+30*60*1000)]);return raw;}
export async function issueSession(account:string){const raw=token();await database().prepare('INSERT INTO sessions(token,account,expires) VALUES(?,?,?)').bind(digest(raw),account,Date.now()+8*60*60*1000).run();return raw;}
export async function sessionUser(req:Request){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)academy_session=([^;]+)/)?.[1];if(!raw)return null;const row=await database().prepare('SELECT a.id,a.email FROM accounts a JOIN sessions s ON s.account=a.id WHERE s.token=? AND s.expires>? AND a.active=1').bind(digest(raw),Date.now()).first();return row?{userId:row.id,email:row.email,displayName:row.email}:null;}
export async function rateLimit(ip:string,email:string){const db=database(),key=digest(ip+'|'+email.toLowerCase()),now=Date.now();await db.prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires<? THEN 1 ELSE count+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END').bind(key,now+15*60*1000,now,now).run();const old=await db.prepare('SELECT count FROM attempts WHERE key=?').bind(key).first();return old.count<=5;}
export async function authenticate(req:Request,ip:string){const body:any=await req.json(),email=String(body.email||'').trim().toLowerCase();if(typeof body.password!=='string'||body.password.length>256||!await rateLimit(ip,email))return Response.json({error:'Unable to sign in. Try again later.'},{status:429});const account=await database().prepare('SELECT * FROM accounts WHERE email=? AND active=1').bind(email).first();const valid=await verifyPassword(body.password,account?.password||('00000000000000000000000000000000:'+('00'.repeat(64))));if(!account||!valid)return Response.json({error:'Email or password is incorrect.'},{status:401});if(account.id!=='academy-owner'){const staff=await database().prepare("SELECT id FROM records WHERE owner='academy-owner' AND kind='staff' AND lower(json_extract(payload,'$.email'))=? AND json_extract(payload,'$.status')='Active'").bind(email).first();if(!staff)return Response.json({error:'Your school access is inactive.'},{status:403});}return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie(await issueSession(account.id))}});}
export async function activate(req:Request,ip:string){const b:any=await req.json();if(typeof b.token!=='string'||b.token.length>128||!await rateLimit(ip,digest(b.token)))return Response.json({error:'Activation unavailable.'},{status:429});if(typeof b.password!=='string'||b.password.length<14||b.password.length>256)return Response.json({error:'Use a password with 14–256 characters.'},{status:400});const db=database(),hash=digest(b.token),row=await db.prepare('SELECT * FROM activations WHERE token=? AND expires>?').bind(hash,Date.now()).first();if(!row)return Response.json({error:'Activation link expired or already used.'},{status:400});const password=await hashPassword(b.password),claimed=await db.prepare('DELETE FROM activations WHERE token=? AND expires>? RETURNING account').bind(hash,Date.now()).first();if(!claimed)return Response.json({error:'Activation already used.'},{status:409});await db.batch([db.prepare('UPDATE accounts SET password=? WHERE id=?').bind(password,claimed.account),db.prepare('DELETE FROM sessions WHERE account=?').bind(claimed.account)]);return Response.json({ok:true},{headers:{'Set-Cookie':sessionCookie(await issueSession(claimed.account))}});}
